# Generated by Django 3.0.5 on 2021-10-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Internship_Applied_For',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='form',
            name='created',
        ),
        migrations.RemoveField(
            model_name='form',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='form',
            name='important',
        ),
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
        migrations.AddField(
            model_name='form',
            name='Internship_Applied_for',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='Phone_No',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='Degree_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='Email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='Specialization',
            field=models.CharField(default='', max_length=100),
        ),
    ]
