# Generated by Django 3.0.5 on 2021-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='College_Name',
            field=models.CharField(max_length=100),
        ),
    ]
